// <auto-generated />
using System;
using Declaration.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Declaration.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240804080329_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Declaration.Core.Entities.DDT", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Cddtage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cddtagr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cddtbur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cddtburdst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cddtcirvis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cddtdep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cddtdevass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cddtdevfle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cddtdevfob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cddtentrep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cddteta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cddtincote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cddtmdetrn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cddtobs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cddtpaidst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cddtpayori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cddtpaytrn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cddttransp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cddtver")
                        .HasColumnType("int");

                    b.Property<DateTime>("Dddtbae")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dddtcancel")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dddtechean")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dddtoficia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dddtrectifa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dddtsalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Iddt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iddtext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iddtextr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lddtagr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lddtnomfod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lddtnomioe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nddtart")
                        .HasColumnType("int");

                    b.Property<int>("Nddtdelai")
                        .HasColumnType("int");

                    b.Property<string>("Nddtimmioe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Qddttaxchg")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("DDTs");
                });
#pragma warning restore 612, 618
        }
    }
}
