// <auto-generated />
using System;
using Declaration.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Declaration.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240804155946_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Declaration.Core.Entities.DDT", b =>
                {
                    b.Property<string>("Iddt")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "Iddt");

                    b.Property<string>("Cddtage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtage");

                    b.Property<string>("Cddtagr")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtagr");

                    b.Property<string>("Cddtbur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtbur");

                    b.Property<string>("Cddtburdst")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtburdst");

                    b.Property<string>("Cddtcirvis")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtcirvis");

                    b.Property<string>("Cddtdep")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtdep");

                    b.Property<string>("Cddtdevass")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtdevass");

                    b.Property<string>("Cddtdevfle")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtdevfle");

                    b.Property<string>("Cddtdevfob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtdevfob");

                    b.Property<string>("Cddtentrep")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtentrep");

                    b.Property<string>("Cddteta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddteta");

                    b.Property<string>("Cddtincote")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtincote");

                    b.Property<string>("Cddtmdetrn")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtmdetrn");

                    b.Property<string>("Cddtobs")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtobs");

                    b.Property<string>("Cddtpaidst")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtpaidst");

                    b.Property<string>("Cddtpayori")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtpayori");

                    b.Property<string>("Cddtpaytrn")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtpaytrn");

                    b.Property<string>("Cddttransp")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddttransp");

                    b.Property<int>("Cddtver")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtver");

                    b.Property<DateTime?>("Dddtbae")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "Dddtbae");

                    b.Property<DateTime?>("Dddtcancel")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "Dddtcancel");

                    b.Property<DateTime?>("Dddtechean")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "Dddtechean");

                    b.Property<DateTime>("Dddtoficia")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "Dddtoficia");

                    b.Property<DateTime?>("Dddtrectifa")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "Dddtrectifa");

                    b.Property<DateTime?>("Dddtsalida")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "Dddtsalida");

                    b.Property<string>("Iddtext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Iddtext");

                    b.Property<string>("Iddtextr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Iddtextr");

                    b.Property<string>("Iext")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Iext");

                    b.Property<string>("Ista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Ista");

                    b.Property<string>("Lddtagr")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Lddtagr");

                    b.Property<string>("Lddtnomfod")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Lddtnomfod");

                    b.Property<string>("Lddtnomioe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Lddtnomioe");

                    b.Property<int>("Nddtart")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "Nddtart");

                    b.Property<int?>("Nddtdelai")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "Nddtdelai");

                    b.Property<string>("Nddtimmioe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Nddtimmioe");

                    b.Property<decimal>("Qddttaxchg")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "Qddttaxchg");

                    b.HasKey("Iddt");

                    b.ToTable("DDTs");
                });
#pragma warning restore 612, 618
        }
    }
}
