// <auto-generated />
using System;
using Declaration.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Declaration.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240805043624_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Declaration.Core.Entities.ART", b =>
                {
                    b.Property<string>("Iddt")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0)
                        .HasAnnotation("Relational:JsonPropertyName", "Iddt");

                    b.Property<int>("Nart")
                        .HasColumnType("int")
                        .HasColumnOrder(1)
                        .HasAnnotation("Relational:JsonPropertyName", "Nart");

                    b.Property<string>("Cartdesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cartdesc");

                    b.Property<string>("Cartetamrc")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cartetamrc");

                    b.Property<string>("Cartpayacq")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cartpayacq");

                    b.Property<string>("Cartpayori")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cartpayori");

                    b.Property<string>("Cartpayprc")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cartpayprc");

                    b.Property<string>("Carttyp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Carttyp");

                    b.Property<string>("Cartuntdcl")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cartuntdcl");

                    b.Property<string>("Cartuntest")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cartuntest");

                    b.Property<string>("Codbenef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Codbenef");

                    b.Property<string>("Iddtapu")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Iddtapu");

                    b.Property<string>("Iespnce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Iespnce");

                    b.Property<decimal?>("Martajuded")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "Martajuded");

                    b.Property<decimal?>("Martajuinc")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "Martajuinc");

                    b.Property<decimal?>("Martass")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "Martass");

                    b.Property<decimal>("Martbasimp")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "Martbasimp");

                    b.Property<decimal?>("Martemma")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "Martemma");

                    b.Property<decimal?>("Martfle")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "Martfle");

                    b.Property<decimal>("Martfob")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "Martfob");

                    b.Property<decimal?>("Martfobdol")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "Martfobdol");

                    b.Property<decimal?>("Martfrai")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "Martfrai");

                    b.Property<decimal?>("Martunitar")
                        .HasColumnType("decimal(18,4)")
                        .HasAnnotation("Relational:JsonPropertyName", "Martunitar");

                    b.Property<int?>("Nartapu")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "Nartapu");

                    b.Property<decimal?>("Qartbul")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "Qartbul");

                    b.Property<decimal?>("Qartkgrbrt")
                        .HasColumnType("decimal(18,3)")
                        .HasAnnotation("Relational:JsonPropertyName", "Qartkgrbrt");

                    b.Property<decimal?>("Qartkgrnet")
                        .HasColumnType("decimal(18,3)")
                        .HasAnnotation("Relational:JsonPropertyName", "Qartkgrnet");

                    b.Property<decimal?>("Qartuntdcl")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "Qartuntdcl");

                    b.Property<decimal?>("Qartuntest")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "Qartuntest");

                    b.HasKey("Iddt", "Nart");

                    b.ToTable("ARTs");
                });

            modelBuilder.Entity("Declaration.Core.Entities.DDT", b =>
                {
                    b.Property<string>("Iddt")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "Iddt");

                    b.Property<string>("Cddtage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtage");

                    b.Property<string>("Cddtagr")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtagr");

                    b.Property<string>("Cddtbur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtbur");

                    b.Property<string>("Cddtburdst")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtburdst");

                    b.Property<string>("Cddtcirvis")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtcirvis");

                    b.Property<string>("Cddtdep")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtdep");

                    b.Property<string>("Cddtdevass")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtdevass");

                    b.Property<string>("Cddtdevfle")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtdevfle");

                    b.Property<string>("Cddtdevfob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtdevfob");

                    b.Property<string>("Cddtentrep")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtentrep");

                    b.Property<string>("Cddteta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddteta");

                    b.Property<string>("Cddtincote")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtincote");

                    b.Property<string>("Cddtmdetrn")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtmdetrn");

                    b.Property<string>("Cddtobs")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtobs");

                    b.Property<string>("Cddtpaidst")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtpaidst");

                    b.Property<string>("Cddtpayori")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtpayori");

                    b.Property<string>("Cddtpaytrn")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtpaytrn");

                    b.Property<string>("Cddttransp")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddttransp");

                    b.Property<int>("Cddtver")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "Cddtver");

                    b.Property<DateTime?>("Dddtbae")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "Dddtbae");

                    b.Property<DateTime?>("Dddtcancel")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "Dddtcancel");

                    b.Property<DateTime?>("Dddtechean")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "Dddtechean");

                    b.Property<DateTime>("Dddtoficia")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "Dddtoficia");

                    b.Property<DateTime?>("Dddtrectifa")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "Dddtrectifa");

                    b.Property<DateTime?>("Dddtsalida")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "Dddtsalida");

                    b.Property<string>("Iddtext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Iddtext");

                    b.Property<string>("Iddtextr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Iddtextr");

                    b.Property<string>("Iext")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Iext");

                    b.Property<string>("Ista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Ista");

                    b.Property<string>("Lddtagr")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Lddtagr");

                    b.Property<string>("Lddtnomfod")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Lddtnomfod");

                    b.Property<string>("Lddtnomioe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Lddtnomioe");

                    b.Property<int>("Nddtart")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "Nddtart");

                    b.Property<int?>("Nddtdelai")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "Nddtdelai");

                    b.Property<string>("Nddtimmioe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Nddtimmioe");

                    b.Property<decimal>("Qddttaxchg")
                        .HasColumnType("decimal(12,6)")
                        .HasAnnotation("Relational:JsonPropertyName", "Qddttaxchg");

                    b.HasKey("Iddt");

                    b.ToTable("DDTs");
                });

            modelBuilder.Entity("Declaration.Core.Entities.LIQ", b =>
                {
                    b.Property<string>("Iliq")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "Iliq");

                    b.Property<string>("Clipnomope")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Clipnomope");

                    b.Property<string>("Cliqdop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cliqdop");

                    b.Property<string>("Cliqeta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Cliqeta");

                    b.Property<DateTime?>("Dlippay")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "Dlippay");

                    b.Property<decimal>("Mliq")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "Mliq");

                    b.Property<decimal>("Mliqgar")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "Mliqgar");

                    b.HasKey("Iliq");

                    b.ToTable("LIQs");
                });

            modelBuilder.Entity("Declaration.Core.Entities.LQA", b =>
                {
                    b.Property<string>("Iliq")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "Iliq");

                    b.Property<int?>("Nart")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "Nart");

                    b.Property<string>("Clqatax")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "Clqatax");

                    b.Property<string>("Clqatyp")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "Clqatyp");

                    b.Property<decimal?>("Mlqa")
                        .HasColumnType("decimal(18,4)")
                        .HasAnnotation("Relational:JsonPropertyName", "Mlqa");

                    b.Property<decimal?>("Mlqabas")
                        .HasColumnType("decimal(18,4)")
                        .HasAnnotation("Relational:JsonPropertyName", "Mlqabas");

                    b.Property<decimal?>("Qlqacoefic")
                        .HasColumnType("decimal(18,6)")
                        .HasAnnotation("Relational:JsonPropertyName", "Qlqacoefic");

                    b.HasKey("Iliq", "Nart", "Clqatax", "Clqatyp");

                    b.ToTable("LAQs");
                });

            modelBuilder.Entity("Declaration.Core.Entities.ART", b =>
                {
                    b.HasOne("Declaration.Core.Entities.DDT", null)
                        .WithMany("ARTS")
                        .HasForeignKey("Iddt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Declaration.Core.Entities.LIQ", b =>
                {
                    b.HasOne("Declaration.Core.Entities.DDT", "DDT")
                        .WithOne("LIQ")
                        .HasForeignKey("Declaration.Core.Entities.LIQ", "Iliq")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DDT");
                });

            modelBuilder.Entity("Declaration.Core.Entities.DDT", b =>
                {
                    b.Navigation("ARTS");

                    b.Navigation("LIQ")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
